Sprint 1
ittySparrow/middle.messenger.praktikum.yandex pull request #1
Opened 2021-07-11 22:51 UTC by ittySparrow

2021-07-12 08:49 UTC, avdoshenkov requested changes
Классная работа, молодец! И в плане кода, и в плане дизайна — очень стильно 👍

Чтобы двигаться дальше нужно несколько мелочей поправить, и ещё не увидел пары страниц из задания:
- изменение пароля
- 404 ошибка
![missings](https://user-images.githubusercontent.com/26881016/125258578-8af10d00-e30f-11eb-99ad-e47b884ef50e.png)

2021-07-12 08:49 UTC, avdoshenkov commented on src/assets/modules/error/error.tmpl.js
> +        <div class="error__title">{{ title }}<span class="error__subtitle">{{ subtitle }}</span></div>
Для заголовков лучше использовать [специальные теги](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements)

2021-07-12 08:49 UTC, avdoshenkov commented on src/assets/modules/profile/profile.tmpl.js
> +          </div>
Для отображения данных вида ключ-значение можно использовать специальный тег [Description List](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl)

2021-07-12 08:49 UTC, avdoshenkov commented on src/assets/modules/register/register.tmpl.js
> +      <button class="btn" type="button" onclick="">{{ button }}</button>
Здесь также для кнопки стоит указать тип `submit`

2021-07-12 08:49 UTC, avdoshenkov commented on src/assets/modules/register/register.tmpl.js
> +          <input type="text" class="form__input" placeholder="{{ label.login }}">
По хорошему у каждого инпута должен быть свой лейбл. Это и с точки зрения семантики, и доступности будет полезно, да и пользователю удобно. Конкретно данный макет, конечно, подталкивает использовать placeholder, но всё же это не лучшее решение. Подробнее можно почитать тут

2021-07-12 08:49 UTC, avdoshenkov commented on src/assets/utils/utils.js
> +export const getObjValue = (obj, path) => {
```suggestion
export const getObjValue = (obj, path, defaultValue = false) => {
```
Переменную `defaultValue` можно вынести в аргументы функции и задать значение по умолчанию, иначе его никак не модифицировать будет в дальнейшем.

2021-07-12 08:49 UTC, avdoshenkov commented on src/index.js
> +  // errorPage()
Закомментированные строки можно смело удалять, чтобы они не замусоривали готовый для продакшена код

2021-07-12 08:49 UTC, avdoshenkov commented on package.json
> +    "handlebars": "^4.7.7"
Поскольку используется свой шаблонизатор, `handlebars` можно смело удалять

2021-07-12 21:35 UTC, ittySparrow commented on .gitignore
> +.idea
done

2021-07-12 21:35 UTC, ittySparrow commented on index.html
> +  <script type="module" src="./src/index.js"></script>
исправила

2021-07-12 21:35 UTC, ittySparrow commented on server.js
> +const PORT = 3000
спасибо за подсказку, исправила в проекте

2021-07-12 21:36 UTC, ittySparrow commented on src/assets/_variables.scss
> +$hover: #434a44;
готово)

2021-07-13 07:07 UTC, avdoshenkov approved these changes
Отлично! Совсем мелочи можно поправить, а так — двигаемся вперёд 💪

2021-07-13 07:07 UTC, avdoshenkov commented on src/assets/modules/error/error404.tmpl.js
> +        <div class="error__back" onclick="{{ toMainPage }}"></div>
Навигацию лучше делать через ссылки (`<a>`), в крайнем случае можно через кнопку, если там какая-то своя логика обработки ещё на права доступа, например, прописана, либо путь динамически составляется. Но по максимуму надо стараться, чтобы ссылки (для доступности очень важно).

2021-07-13 07:07 UTC, avdoshenkov commented on src/assets/modules/profile/profile.tmpl.js
> +            <div class="profile__edit-item" onclick="{{ openEditPasswordPage }}">{{ changePassword }}</div>
Тут тоже лучше ссылками/кнопками сделать

2021-08-04 08:43 UTC, merged